version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    ports:
      - "9092:9092"
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "BOOKS_LOG:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
