spring:
   kafka:
      bootstrap-servers: localhost:9092
      listener:
         ack-mode: record
      consumer:
         group-id: books
         auto-offset-reset: latest
      producer:
         acks: all
         retries: 5
         compression-type: snappy

application:
   kafka:
      topic: BOOKS_LOG